apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drkiq-postgres
  labels:
    db: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
